[package]
name = "neo"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1.41", features = ["attributes", "release_max_level_off"] }
tracing-subscriber = { version= "0.3.19", features = ["env-filter"] }
